services:
  postgres:
    image: postgres:18
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: medicare
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
  mongodb:
    image: mongo:8.3
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: medicare
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  pgdata:
  mongodata: